INSERT INTO USER (USERID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES ('test1','pass','test1','test1@test.com', CURRENT_TIMESTAMP());
INSERT INTO USER (USERID, PASSWORD, NAME, EMAIL, CREATE_DATE) VALUES ('test2','pass','test2','test2@test.com', CURRENT_TIMESTAMP());

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE, count_of_answer) VALUES (1, 1,'TEST TITLE','TEST C',CURRENT_TIMESTAMP(),0);