INSERT INTO USER (USERID, PASSWORD, NAME, EMAIL) VALUES ('test1','pass','test1','test1@test.com');
INSERT INTO USER (USERID, PASSWORD, NAME, EMAIL) VALUES ('test2','pass','test2','test2@test.com');

INSERT INTO QUESTION (ID, WRITER_ID, TITLE, CONTENTS, CREATE_TIME) VALUES (1, 1,'TEST TITLE','TEST C',CURRENT_TIMESTAMP());